# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.1

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            set -x
            mkdir artifacts
            sudo pip install -r requirements.txt -t artifacts
            cp -v ami_builder.py LICENSE packer_template.json.j2 README.md artifacts
            curl -O https://releases.hashicorp.com/packer/1.4.4/packer_1.4.4_linux_amd64.zip
            cd artifacts
            unzip ../packer_1.3.3_linux_amd64.zip
            LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
            VERSION=$(echo $LATEST_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            VERSION_NUMBER=$(echo $VERSION | sed 's/^v\(.*\)$/\1/')
            zip -r ami-builder-$VERSION_NUMBER.zip *

      - persist_to_workspace:
          root: artifacts
          paths:
            - ami-builder-*.zip
  publish-github-release:
      docker:
        - image: cibuilds/github:0.10
      steps:
        - attach_workspace:
            at: ./artifacts
        - run:
            name: "Publish Release on GitHub"
            command: |
              LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
              VERSION=$(echo $LATEST_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
              echo "ghr -t GITHUB_TOKEN -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/"
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: master
